---
trigger:
- the-first-pipeline

pool:
  vmImage: ubuntu-latest

steps:

- checkout: none

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: python -m pip install "molecule[lint]" "python-vagrant" "molecule-vagrant" "ansible"
  displayName: Install dependencies

- script: python -m pip install "python-tss-sdk"
  displayName: Role-specific dependencies

- script: |
    export PATH="$PATH:/home/<user>/.local/bin/"
    cd $(Agent.BuildDirectory)/webserver
    molecule test
  displayName: Test relevant platforms