---
- name: Install epel-release
  yum:
    name: epel-release
    state: present
    update_cache: true 

- name: Install a list of packages with a list variable
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - httpd
    - httpd-tools
    - firewalld

- name: "Ensure httpd service is started and enabled"
  service:
    name: httpd
    state: started
    enabled: true

- name: "Ensure firewalld service is started and enabled"
  service:
    name: firewalld
    state: started
    enabled: true