---
trigger:
- the-first-pipeline

pool:
  vmImage: ubuntu-latest

steps:


- task: CopyFiles@2
  displayName: 'Copy file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    OverWrite: true 
    Contents: |
      **/*
    TargetFolder: '/tmp'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'



- script: |
    pipenv shell
    python -m pip install "molecule[lint]" "python-vagrant" "molecule-vagrant" "ansible" 

  displayName: Install dependencies

- script: |
    cd /tmp/webserver
    molecule test
  displayName: Pipeline Tests