---
trigger:
- the-first-pipeline

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- task: CopyFiles@2
  displayName: 'Copy file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    OverWrite: true 
    Contents: |
      **/ansible-molecule/webserver/**
    TargetFolder: '/tmp'

#- script: |
#     cd /tmp/ansible-molecule/webserver
#     python3 -m venv .venv && source .venv/bin/activate
#     python3 -m pip install "molecule[docker,lint]"
#     python3 -m pip install "wheel"
#     python3 -m pip install "ansible"
#     python3 -m pip install "pytest"
#     python3 -m pip install "testinfra" 
#     python3 -m pip install "python-tss-sdk"
#     molecule -vvvv test 
#  displayName: Install dependencies 


- script: |
    cd /tmp/ansible-molecue/webserver/
     python3 -m pip install "molecule[docker,lint]"
     python3 -m pip install "wheel"
     python3 -m pip install "ansible"
     python3 -m pip install "pytest"
     python3 -m pip install "testinfra" 
     python3 -m pip install "python-tss-sdk"

  displayName: Install dependencies

- script: |
    cd /tmp/ansible-molecue/webserver/
    source .venv/bin/activate
    molecule test
  displayName: Pipeline Tests