---
trigger:
- the-first-pipeline

pool:
  vmImage: ubuntu-latest

steps:


#- task: CopyFiles@2
#  displayName: 'Copy file'
#  inputs:
#    SourceFolder: '$(Build.SourcesDirectory)'
#    OverWrite: true 
#    Contents: |
#      **/*
#    TargetFolder: '/tmp'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'



- script: |

    python3 -m venv .venv && source .venv/bin/activate
    python3 -m pip install "molecule[docker,lint]"
    python3 -m pip install "whell"
    python3 -m pip install "ansible"

  displayName: Install dependencies

#- script: |
#    pipenv shell
#    cd /tmp/webserver
#    molecule test
#  displayName: Pipeline Tests