---
trigger:
- the-first-pipeline

pool:
  vmImage: ubuntu-latest

steps:

- checkout: none

- task: CopyFiles@2
  displayName: 'Copy file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    OverWrite: true 
    Contents: |
      '$(Build.SourcesDirectory)/ansible-molecule/webserver/tasks/**'
      '$(Build.SourcesDirectory)/ansible-molecule/webserver/molecule/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/tmp'

#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '3.8'



#- script: |
#    pipenv shell
#    python -m pip install "molecule[lint]" "python-vagrant" "molecule-vagrant" "ansible" 
#
#  displayName: Install dependencies
#
#- script: |
#    export PATH="$PATH:/home/<user>/.local/bin/"
#    cd $(Agent.BuildDirectory)/webserver
#    molecule test
#  displayName: Test relevant platforms